# default configuration
baseURL = "https://ashutoshtiwari13.github.io"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "<Ashutosh Tiwari/>"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "publication"
name = "Publications"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Projects"
weight = 3

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 4

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5

# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#632d17"
# contact info
phone = "+91-9845942478"
email = "reachatashutosh@gmail.com"
address = "Bengaluru, India"
# meta description
author = "Ashutosh Tiwari"
description = "Developer at Night. Loves to code. "
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Made with ☕️ By Ashutosh Tiwari"


# preloader
[params.preloader]
enable = true
preloader = "images/start.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# social site
[[params.social]]
icon = "ti-github"
URL = "#"

[[params.social]]
icon = "ti-youtube"
URL = "#"


[[params.social]]
icon = "ti-linkedin"
URL = "#"

[[params.social]]
icon = "ti-instagram"
URL = "#"

[[params.social]]
icon = "ti-twitter-alt"
URL = "#"
